### ISSUE TITLE
Default site url set when update uvdesk.yaml[email settings]

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/mailbox-component#13]
**current site url**

![Screenshot12](https://user-images.githubusercontent.com/43210406/57301753-595cd580-70f7-11e9-9b4c-1a38d50bd7f3.png)

**Issue : default site_url set after update email settings**

![Screenshot](https://user-images.githubusercontent.com/43210406/57301823-7beeee80-70f7-11e9-844c-0e4ed6d8f6c1.png)

**Comment by kumarSaurabh27** [comment]
Resolved  https://github.com/uvdesk/core-framework/pull/139

**Comment by kumarSaurabh27** [comment]
Updated
