### ISSUE TITLE
duplicate swiftmailer created with same email

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/mailbox-component#14]
**Note:** duplicate swiftmailer show only on swiftmailer.yaml but does not reflect on UI end.

![Screenshot13](https://user-images.githubusercontent.com/43210406/57302690-6084e300-70f9-11e9-9135-721b99a3ff44.png)

**Comment by kumarSaurabh27** [comment]
Resolved https://github.com/uvdesk/core-framework/pull/138

**Comment by kumarSaurabh27** [comment]
Updated  and resolved https://github.com/uvdesk/core-framework/pull/139

**Comment by vaishaliwebkul** [comment]
Hi @kumarSaurabh27 

I am facing the exact issue while updating exisitng swiftmailer configuration with same id as another configuration..

![Awesome1](https://user-images.githubusercontent.com/43210406/60703120-91796c80-9f1e-11e9-8471-9a5715907cb7.png)
