### ISSUE TITLE
Swiftmailer gets deleted for setup mailbox

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/mailbox-component#15]
### Swiftmailer should not be deleted if mailbox using that id [use swiftmailer id]

![Screenshot14](https://user-images.githubusercontent.com/43210406/57303614-549a2080-70fb-11e9-99b8-3bbca58eb61f.png)

**Comment by kumarSaurabh27** [comment]
Fixed. While deleting swiftmailer config. , the mailbox config. gets deleted if mailbox is using the same id as of swiftmail.
https://github.com/uvdesk/core-framework/pull/151

**Comment by vaishaliwebkul** [comment]
Hi @kumarSaurabh27 

Mailbox got disabled if delete swiftmailer, but when click to edit mailbox button ,getting below issue: 

![Awesome2](https://user-images.githubusercontent.com/43210406/60704122-2ed5a000-9f21-11e9-9f3b-89fad99e4232.png)
