### ISSUE TITLE
yahoo configuration issue with user password 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/mailbox-component#18]
**_found password field label with username in the code[uvdesk_mailbox.yaml]_ for yahoo configuration**

![Screenshot17](https://user-images.githubusercontent.com/43210406/57356840-1c442200-718f-11e9-9bdc-105904b3f70c.png)

**Comment by kumarSaurabh27** [comment]
Resolved   https://github.com/uvdesk/core-framework/pull/138
