### ISSUE TITLE
Port not define for mailbox when set transport as IMAP

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/mailbox-component#20]
Verify and test mailbox by **selecting imap as transport** from drop down menu
Configuration save but when edit mailbox then getting issue

![Screenshot43](https://user-images.githubusercontent.com/43210406/58103274-589c6700-7c00-11e9-9d99-5a3da3081395.png)

![Screenshot - 2019-05-21T194234 634](https://user-images.githubusercontent.com/43210406/58103445-9bf6d580-7c00-11e9-9b14-34ba92046565.png)

uvdesk_mailbox.yaml

![Screenshot55](https://user-images.githubusercontent.com/43210406/58366328-3cdddd00-7eee-11e9-8e2f-cd98722cace5.png)

**Comment by kumarSaurabh27** [comment]
Resolved.
