### ISSUE TITLE
Swiftmailer update with blank mailer_id

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/mailbox-component#22]
Update  swiftmailer configuration by passing blank mailer_id.
**Error comes as mention below**

![Screenshot57](https://user-images.githubusercontent.com/43210406/58367866-30fc1600-7f02-11e9-8927-8ddf876e5b3f.png)

**Comment by kumarSaurabh27** [comment]
Resolved   https://github.com/uvdesk/core-framework/pull/138
