### ISSUE TITLE
Sender address and delivery address not save into swiftmailer.yaml

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/mailbox-component#25]
**When select transport type: SMTP**
sender address and delivery address field data do not save into swiftmailer.yaml

Add address field
![Screenshot(1)](https://user-images.githubusercontent.com/43210406/59261027-573be880-8c5a-11e9-8f0c-d1c8f51ae63b.png)

Field in the file not save
![Screenshot72](https://user-images.githubusercontent.com/43210406/59261079-6fac0300-8c5a-11e9-8a37-0cec3bfcee8e.png)

**Comment by kumarSaurabh27** [comment]
Resolved https://github.com/uvdesk/core-framework/pull/144

**Comment by vaishaliwebkul** [comment]
Undefined method call inside Gmail configuration, also checks same for SMTP, yahoo configuration.

![Screenshot88](https://user-images.githubusercontent.com/43210406/59999153-eb587780-967e-11e9-9711-85e33d48cfcd.png)

**Comment by kumarSaurabh27** [comment]
Fixed  https://github.com/uvdesk/core-framework/pull/151
