### ISSUE TITLE
Unable to set swiftmailer configuration from yahoo to smtp transport

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/mailbox-component#34]
### Issue-  Swiftmailer.yaml files gets update but configuration not update on front end.

**Comment by kumarSaurabh27** [comment]
If host provided is '**smtp.mail.yahoo.com**' while reckoning swiftmailer configuration, then the transport will be **Yahoo**. Any other host other than 'smtp.mail.yahoo.com' , while adding swiftmailer configuration will show **SMTP** transport.

**Comment by vaishaliwebkul** [comment]
Fixed
