### ISSUE TITLE
Duplicate entry for ticket when running refresh command second time. 

### ISSUE THREAD

**Issue by rahulshukla-webkul** [uvdesk/mailbox-component#51]
When an email is received, the ticket is created by using refresh mailbox command.
But when I run refresh command again the same message is recorded again inside ticket(like a reply), like the customer has answered the confirmation email.
But it is no answer from the customer, there is only one email!

**Comment by papnoisanjeev** [comment]
@rahulshukla-webkul 
locate file in your project.

**vendor->uvdesk->mailbox-component->Services->MailboxService.php**

Open **MailboxService.php**  and reach to **processMail()** function.

![refreshMailduplicate](https://user-images.githubusercontent.com/42460055/73119428-9e77af00-3f87-11ea-970e-eb69b66c98b0.png)

Add condition as shown in screen shot.
