### ISSUE TITLE
Mailbox \ Mailbox Refreshed successfully but no tickets  created

### ISSUE THREAD

**Issue by Fatim671** [uvdesk/mailbox-component#53]
Hi,
I have completed the mailbox configuration in the uvdesk, the php bin/console uvdesk:refresh-mailbox xxxx@xxxxx.com is resulting  yet no tickets created.
Converting email 61 out of 61.
Mailbox refreshed successfully !!!

Please advise,
Fatima

**Comment by papnoisanjeev** [comment]
@Fatim671 

Check your **site_url**  in **uvdesk.yaml**  file under **config->packages**.
Update your site URL here.

**Comment by Fatim671** [comment]
Thank you papnoisanjeev ,
should it be a public IP?

**Comment by Himaniwebkul** [comment]
@Fatim671 
It will be the localhost or domain path till public, 
For example: localhost/folder_name/public
For more details, you can refer to this video - https://youtu.be/2KsECEkvuDM

**Comment by Fatim671** [comment]
Thank you Himaniwebkul,

It is set as localhost/uvdesk/public yet same issue. Below is my current configuration.

![1](https://user-images.githubusercontent.com/62341146/77048950-e89d6f80-69cf-11ea-9f9b-b962fdff99dc.jpg)
![2](https://user-images.githubusercontent.com/62341146/77048958-ecc98d00-69cf-11ea-9ffb-17eb5662c186.jpg)
![3](https://user-images.githubusercontent.com/62341146/77049325-90b33880-69d0-11ea-8c11-ae11752918dc.jpg)
![4](https://user-images.githubusercontent.com/62341146/77049329-91e46580-69d0-11ea-90d5-41e44d6c6ced.jpg)

**Comment by papnoisanjeev** [comment]
@Fatim671 

Open your project directory and locate path.
**vendor->uvdesk->mailbox-component->Console->RefreshMailboxCommand.php**

**OpenRefreshMailboxCommand.php** and reach to the  **pushMessage()** function.

Now check step by step by dumping each step while running the refresh mailbox command.

Here you can check  $curlResponse  by  **dump( $curlResponse); die;**

![202001205e256198138d4refreshMailbox](https://user-images.githubusercontent.com/42460055/77053427-565b9280-69f4-11ea-8872-5713bd1e8d35.png)


If you still you are not able to figure it out create a [support ticket](https://support.uvdesk.com/en/customer/create-ticket/) or you can directly mail us us at support@uvdesk.com.

**Comment by Fatim671** [comment]
Hi papnoisanjeev,

Adding the dump gives the below output, what is the **false** here?
![image](https://user-images.githubusercontent.com/62341146/77435173-a4083e80-6dea-11ea-9da6-ffba4f46cf51.png)

**Comment by papnoisanjeev** [comment]
@Fatim671 
It means your mails are fetching successfully but when it is converting as a ticket something is wrong here so mails are not converting into tickets.
please check step by step by dumping all things like $requestUrl and other things if these are correct or not.

If still facing issue create a support ticket [here](https://support.uvdesk.com/en/customer/create-ticket/).
