### ISSUE TITLE
Imap stream can't be oppened

### ISSUE THREAD

**Issue by nakigami** [uvdesk/mailbox-component#55]
Hi,
I configured mailbox correctely and i enabled less security in my email, but when i tried the command php bin/console uvdesk:refresh-mailbox MY_EMAIL i figured out that the imap stream couldn't be oppened (extension imap is enabled, openssl also enabled, gd2 also enabled ), i got this error : 
-----------------------------------------------------------

PHP Warning:  PHP Startup: Unable to load dynamic library 'gd2' (tried: /usr/lib/php/20170718/gd2 (/usr/lib/php/20170718/gd2: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/gd2.so (/usr/lib/php/20170718/gd2.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20170718/mysqli (/usr/lib/php/20170718/mysqli: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/mysqli.so (/usr/lib/php/20170718/mysqli.so: undefined symbol: mysqlnd_global_stats)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl' (tried: /usr/lib/php/20170718/openssl (/usr/lib/php/20170718/openssl: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/openssl.so (/usr/lib/php/20170718/openssl.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20170718/pdo_mysql (/usr/lib/php/20170718/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/pdo_mysql.so (/usr/lib/php/20170718/pdo_mysql.so: undefined symbol: mysqlnd_allocator)) in Unknown on line 0
PHP Warning:  Module 'exif' already loaded in Unknown on line 0
PHP Warning:  Module 'imap' already loaded in Unknown on line 0
PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0

 1. Processing uvdesk mailbox configuration.

 2. Opening imap stream...

In RefreshMailboxCommand.php line 88:

  Warning: imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl/novalidate-cert}

uvdesk:refresh-mailbox [-t|--timestamp TIMESTAMP] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<emails>...]

PHP Fatal error:  Uncaught ErrorException: Notice: Unknown: Retrying PLAIN authentication after [AUTHENTICATIONFAILED] Invalid credentials (Failure) (errflg=1) in Unknown:0
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError(8, 'Unknown: Retryi...', 'Unknown', 0, NULL)
#1 {main}
  thrown in Unknown on line 0

**Comment by papnoisanjeev** [comment]
@nakigami 

> Use Host as  {imap.gmail.com:993/imap/ssl}INBOX for gmail.
> Double check your credentials as error showing  **Invalid credentials** used.

**Comment by nakigami** [comment]
hi, still getting the same error i changed the gmail account, i enabled imap on gmail account, i activated less secure app on gmail but still getting this : 
 1. Processing uvdesk mailbox configuration.

 2. Opening imap stream...

In RefreshMailboxCommand.php line 88:

  Warning: imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl}INBOX


uvdesk:refresh-mailbox [-t|--timestamp TIMESTAMP] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<emails>...]

PHP Fatal error:  Uncaught ErrorException: Notice: Unknown: Retrying PLAIN authentication after [ALERT] Please log in via your web browser: https://support.google.com/mail/acco (errflg=1) in Unknown:0
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError(8, 'Unknown: Retryi...', 'Unknown', 0, NULL)
#1 {main}
  thrown in Unknown on line 0

**Comment by vaishaliwebkul** [comment]
@nakigami 
please follow the solution provided here https://stackoverflow.com/questions/11772240/connecting-to-gmail-imap-php-couldnt-open-stream
you may also check the userguide https://www.uvdesk.com/en/blog/setup-mailbox-uvdesk-open-source-helpdesk/

PS:- Don't forget to add valid app_url in uvdesk.yaml file and then clear the project cache.
