### ISSUE TITLE
MailboxService fails to create new ticket when to is not canonically defined

### ISSUE THREAD

**Issue by quazardous** [uvdesk/mailbox-component#58]
**Description**  
When you deal with IMAP boxes you sometimes have mails without correct **to** field (moved email or so).
But the MailboxService tries to rely on the **to** field to guess the correct mailbox to use. And OC it fails.

**How to reproduce**  
I just guess because it's a mail I had in production environnement with a client. I think you have to create a mail directly in an IMAP box and move it in the INBOX folder.

**Possible Solution**  
Inject the canonical email at first position in the to addresses array in the parser.

**Additional context**

**Comment by papnoisanjeev** [comment]
@quazardous 

Thanks for your suggestion !!
You can create a pull request for the same we will review if everything goes ok will add it.

**Comment by quazardous** [comment]
I'll try if I have some time

The simplest lead I've think of is to add a `$mailboxEmail` param to `public function processMail($rawEmail, $mailboxEmail = null)` so it's up to the caller to add (or not) this sanity check.

It would be convenient to isolate the parse code in a `parseMail($rawEmail, $mailboxEmail = null)` function.

```php
public function parseMail($rawEmail, $mailboxEmail = null)
{
    ...
    if ($mailboxEmail) {
        if (!in_array($mailboxEmail, $mailData['replyTo'])) array_unshift($mailData['replyTo'], $mailboxEmail);
    }
    return $mailData;
}
```

We should ensure that `ticket.service:createTicket()` uses the first email 

```php
//$params['mailboxEmail'] = current($params['replyTo']); 
$params['mailboxEmail'] = reset($params['replyTo']); 
```

**Comment by jmrventura92** [comment]
Maybe this is related to my issue? #65

**Comment by papnoisanjeev** [comment]
@jmrventura92 

Please check [this ](https://github.com/uvdesk/mailbox-component/issues/64#issuecomment-788920997) update if it solve your issue.
