### ISSUE TITLE
The new MailboxService.php  did not open ticket from emails

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/mailbox-component#67]
https://forums.uvdesk.com/topic/1840/add-google-recaptcha/45

As described in the forum the new MailboxService.php is broken as is not opening ticket received by email.
For be sure to have the correct file I not just only copied and replaced the file content but also downloaded the latest zip file from https://github.com/uvdesk/mailbox-component/archive/refs/heads/master.zip

As soon I replace the file and clear caxche then test... I see email are flagged as read but no ticket is created.
For resolve I need to resume my old MailboxService.php and all work back normally.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Check [here](https://forums.uvdesk.com/topic/1840/add-google-recaptcha/54).

**Comment by PeopleInside** [comment]
@papnoisanjeev I tested (not today) the new Mail file and is not working for me so the file is broken or you need understand what process suggest to upgrade existing install as ticket are no more created if I put this new file.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

please verify again.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Closing this issue currently if you are still facing it then you can reopen.

**Comment by PeopleInside** [comment]
@papnoisanjeev this seems works.
Ticket is created, I will try to monitor and test more to be sure was not inserted some new bugs.

Thanks.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

You can test with more cases and report to us if any issue exist.

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside
> 
> You can test with more cases and report to us if any issue exist.

Sure, thanks

**Comment by PeopleInside** [comment]
> Closing this issue currently if you are still facing it then you can reopen.

PS: I forget, when you close a user issue the user cannot open anymore. Just to let you know, this is how GitHub works. Only if user close the issue will be able to open again :)

What can do user is comment and report the issue was not resolved.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

>> PS: I forget, when you close a user issue the user cannot open anymore. Just to let you know, this is how GitHub works. Only if user close the issue will be able to open again :)

But can still comment on issue or can generate a same issue again :)

**Comment by PeopleInside** [comment]
I tested more and seems for me works means:
Works on ticket opening by web or email and also on ticket reply so seems good.
Thanks

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Thanks for your time 👍

**Comment by PeopleInside** [comment]
> 
> 
> @PeopleInside
> 
> Thanks for your time 👍

Oh, this is very nice!
For test your update and file I create a new instance and email address all the time so take times and work.. I never told this but is what I done also today and in the past days.

I try to use this way for avoid issue on my stable version where updates create some issues due to bugs, etc so I decide to test in separate way.

If I was in a better job position (I'm not working) I would be happy to sponsor, donate you... so I'm happy to try to repay you with my time and some advice. Is the minimum I can do.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

> so I'm happy to try to repay you with my time and some advice. Is the minimum I can do.

It means a lot for us you are giving your precious time to support this project.
