### ISSUE TITLE
upgrade php-mime-mail-parser version to 7

### ISSUE THREAD

**Issue by temiotu** [uvdesk/mailbox-component#69]
Can you upgrade to php-mime-mail-parser 7?
This will enable me to deploy to heroku. 
Version 3.0.4 of mail parser requires php 7.0 which is no longer available on heroku. They support > = 7.3.24

**Comment by papnoisanjeev** [comment]
@temiotu 

Currently project support php version >= 7.2.
Please show us where you want to make a package version update.

**Comment by Komal-sharma-2712** [comment]
@temiotu 
We are closing this issue 
if still you are facing issue then you can reply on same mesage thread.
