### ISSUE TITLE
Mailbox component doesn't extract inline image as attachment

### ISSUE THREAD

**Issue by cney-afluens** [uvdesk/mailbox-component#80]
**Description**  

The images embeded in email are posted as content and not extracted as attachment, this conducts to very large database and ends in uvdesk crashing when loading tickets.

**How to reproduce**  

Send an email from Gmail with an inline image (not an attachment)

**Possible Solution**  

Email content needs to be parsed and images removed or posted as attachment.

**Additional context**

**Comment by vipin-shrivastava** [comment]
@cney-afluens 

Thank you & provide some more information regarding this issue. As we check with inline 15-20 images sent with Gmail in multiple replies of tickets but we didn't face any issue.

**Comment by Komal-sharma-2712** [comment]
@cney-afluens 
Now, this issue is solved with inline images attached from the email side

![image](https://user-images.githubusercontent.com/63539748/161238820-0d6f36e7-5f0f-4bd1-9483-eb213698d559.png)

so we are closing this issue if you still facing the same issue so reply in the same thread.
