### ISSUE TITLE
mail to ticket conversion stops with Error ->

### ISSUE THREAD

**Issue by aseedorf** [uvdesk/mailbox-component#86]
fetching mail from imap-server works fine but when trying to convert mail to ticket by cli-command the following eror occours:

 1. Processing uvdesk mailbox configuration.

 2. Opening imap stream...

 3. IMAP stream opened.

 4. Fetching Email collection since 29 November 2021.

 5. Total fetched email -> 1

 6. Starting to convert Emails into Tickets ->
=============================================
=============================================

  Converting email 1 out of 1.

  Error ->

no more info on output is available, because the is no other error-message

**Comment by papnoisanjeev** [comment]
@aseedorf 

Please check if  **Mailparse** and **php-curl** extension enabled on your server.

**Comment by aseedorf** [comment]
i have checked ist, both php-modules are installes and enabled.
i used the following tutorial for installation:
https://computingforgeeks.com/setup-uvdesk-ticketing-system-on-ubuntu/

**Comment by Komal-sharma-2712** [comment]
@aseedorf 
We are closing this issue
if still, you are facing any issue then you can reply on the same message thread.
